export const projectsData = [
    {
        id: 1,
        title: "E-commerce Website",
        description: "A full-stack e-commerce website built with React, Node.js, Express, and MongoDB.",
        image: "https://i.ibb.co/7J9X8J6/ecommerce.png",
        technologies: ["ReactJS", "NodeJS", "Express", "MongoDB"],
        link: "/",
    },
    {
        id: 2,
        title: "Social Media App",
        description: "A full-stack social media application built with React, Node.js, Express, and MongoDB.",
        image: "https://i.ibb.co/7J9X8J6/ecommerce.png",
        technologies: ["ReactJS", "NodeJS", "Express", "MongoDB"],
        link: "/",
    },
    {
        id: 3,
        title: "Weather App",
        description: "A weather application built with React and the OpenWeatherMap API.",
        image: "https://i.ibb.co/7J9X8J6/ecommerce.png",
        technologies: ["ReactJS", "OpenWeatherMap API"],
        link: "/",
    },
    {
        id: 4,
        title: "Task Manager App",
        description: "A task manager application built with React, Node.js, Express, and MongoDB.",
        image: "https://i.ibb.co/7J9X8J6/ecommerce.png",
        technologies: ["ReactJS", "NodeJS", "Express", "MongoDB"],
        link: "/",
    },
    {
        id: 5,
        title: "Blog Website",
        description: "A full-stack blog website built with React, Node.js, Express, and MongoDB.",
        image: "https://i.ibb.co/7J9X8J6/ecommerce.png",
        technologies: ["ReactJS", "NodeJS", "Express", "MongoDB"],
        link: "/",
    },
    {
        id: 6,
        title: "Portfolio Website",
        description: "A personal portfolio website built with React.",
        image: "https://i.ibb.co/7J9X8J6/ecommerce.png",
        technologies: ["ReactJS"],
        link: "/",
    },
];
